M48
; DRILL file {KiCad 6.0.2+dfsg-1} date Thu 29 Jun 2023 12:19:00 PM MDT
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-06-29T12:19:00-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.2+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
%
G90
G05
T1
X-26.26Y31.496
X-19.46Y31.496
T2
X-72.644Y30.05
T0
M30
