M48
; DRILL file {KiCad 6.0.2+dfsg-1} date Wed 28 Jun 2023 01:43:02 PM MDT
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-06-28T13:43:02-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.2+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
%
G90
G05
T1
X-178.905Y28.753
X-178.905Y-2.947
X-126.905Y28.753
X-126.905Y-2.947
T2
X-109.189Y30.048
X-72.39Y30.05
T0
M30
